// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
namespace Library
{
		public class Accelerometer
		{
			static public bool forcedGesture(Vector3 accelerometer) {
				return Mathf.Abs(accelerometer.x) > 1.1f || Mathf.Abs (accelerometer.y) > 1.1f || Mathf.Abs (accelerometer.z) > 1.1f;
			}
		}
}

